### ISSUE TITLE
Investigate official Microsoft support

### ISSUE THREAD

**Issue by hoovercj** [zodiacfireworks/vscode-c-al#1]
The Dynamics NAV team has support for VS Code described in this [overview](https://msdn.microsoft.com/en-us/dynamics-nav/newdev-dev-overview) and this [getting started guide](https://msdn.microsoft.com/en-us/dynamics-nav/newdev-get-started)

You can learn more and get updates on the [NAV blog](https://blogs.msdn.microsoft.com/nav/)

**Comment by zodiacfireworks** [comment]
@hoovercj, thanks for the information, I was looking for the official support but I was not lucky. Sadly my free trial subscription ends.
