### ISSUE TITLE
We'd like to talk about contributing

### ISSUE THREAD

**Issue by stuartglasson** [zodiacfireworks/vscode-c-al#2]
Hello,
We've seen your extension on the VS Code marketplace and would like to talk about the contribution.
Can you please get in touch with us at Microsoft.  I'm the Program Manager on the C/AL team and you can reach me at sglasson@microsoft.com
Thanks,
Stuart

**Comment by zodiacfireworks** [comment]
Hi, @stuartglasson, sorry for the late reply. I sent you an email.

**Comment by nareshwar** [comment]
Hello,

This extension is fabulous. Just started using it and definitely love to contribute. Please drop me a mail too: rajnareshwar@gmail.com
