### ISSUE TITLE
No colors on .cal file

### ISSUE THREAD

**Issue by warlof** [zodiacfireworks/vscode-c-al#4]
Hello,

I'm expecting an issue with this extension which is not coloring my c/al code.
I think i've miss something somewhere but in your readme you didn't write any specific setup instructions :(

I've just installed the extension in visual code and create a simple file called codeunit50000.cal with this content :

```
OBJECT Codeunit 50000 EDIFACT Order
{
  OBJECT-PROPERTIES
  {
    Date=27/07/17;
    Time=20:11:44;
    Modified=Yes;
    Version List=Test;
  }
  PROPERTIES
  {
    OnRun=BEGIN
    END;
  }
  CODE
  {
    LOCAL PROCEDURE formatFile@1000000003(VAR buffer@1000000000 : Text);
    VAR
      CR@1000000001 : Char;
      LF@1000000002 : Char;
    BEGIN
      CR := 13;
      LF := 10;

      buffer := DELCHR(buffer, '=', FORMAT(CR));
      buffer := DELCHR(buffer, '=', FORMAT(LF));
    END;

    BEGIN
    {
        // Test
    }
    END.
  }
}
```

**Comment by zodiacfireworks** [comment]
Hello @warlof!

Thanks for report. 

This is strange but this was due a comment in c-al-tmLanguage.json file. I deleted such comment and the colors came back.

Please update the [extension](https://marketplace.visualstudio.com/items?itemName=zodiacfireworks.vscode-c-al) in your vscode.

![screenshot from 2017-07-31 06-58-51](https://user-images.githubusercontent.com/4976355/28776770-bf4c52c6-75bd-11e7-846e-ed3ee626424b.png)
